# Generated by Django 3.1.7 on 2021-04-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('sinopse', models.TextField()),
                ('img', models.ImageField(upload_to='images/')),
                ('generos', models.CharField(max_length=80)),
                ('duracao', models.CharField(max_length=30)),
                ('diretor', models.CharField(max_length=50)),
            ],
        ),
    ]
