# Generated by Django 3.1.7 on 2021-04-03 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmes',
            old_name='img',
            new_name='image',
        ),
    ]
