# Generated by Django 3.1.7 on 2021-04-13 12:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_auto_20210412_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='filmes_favoritos', to=settings.AUTH_USER_MODEL),
        ),
    ]
