# Generated by Django 3.1.7 on 2021-04-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210413_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
